### ISSUE TITLE
Enhancement request - shared IP for TCP and UDP load balancer services

### ISSUE THREAD

**Issue by sammcgeown** [kube-vip/kube-vip-cloud-provider#4]
Hi,

I'm currently using kube-vip and metallb, I'd like to switch over to using kube-vip for my load balancers (love the DHCP option) but I need to be able to have TCP and UDP services sharing an IP address (with metallb I can annotate with `metallb.universe.tf/allow-shared-ip: sharedservicename`)

Is there a plan to introduce something similar, or is this not a possibility?

**Comment by thebsdbox** [comment]
https://github.com/kube-vip/kube-vip/issues/191 <- This should be an option that you can enable

**Comment by sammcgeown** [comment]
Thanks @thebsdbox - I searched over on the old repo but missed that one.

I can confirm I've just added the feature gate by editing `/etc/kubernetes/manifests/kube-apiserver.yaml` on each master and adding `    - --feature-gates=MixedProtocolLBService=true` to the command section. This restarts the kube-apiserver automatically and allows me to create services with both TCP and UDP - e.g.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/instance: definit-plex
  name: plex-ui
  namespace: plex
spec:
  ports:
    - name: pms-http
      port: 32400
      protocol: TCP
    - name: pms-dlna
      port: 32469
      protocol: TCP
    - name: pms-udp
      port: 32400
      protocol: UDP
    - name: pms-dlna-udp
      port: 32469
      protocol: UDP
    - name: pms-dlna-udp-2
      port: 1900
      protocol: UDP
    - name: pms-bonjour
      port: 5353
      protocol: UDP
  selector:
    app.kubernetes.io/name: plex-media-server
    app.kubernetes.io/instance: definit-plex
  type: LoadBalancer
```
